default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: url_shortner_dev

test:
  <<: *default
  database: url_shortner_test

production:
  <<: *default
  database: url_shortner_production
  username: url_shortner
  password: <%= ENV["URL_SHORTNER_DATABASE_PASSWORD"] %>
